### ISSUE TITLE
Deposit Liquidity - LP

### ISSUE THREAD

**Issue by 0xksure** [Sure-Protocol/sure-v1#6]
Implement liquidity providing at ticks. 
Track which ticks contain liquidity by implementing a basic bitmap. 

See documentation at https://sure-claims.slite.com/app/docs/ECijzeX6jc_Ype

**Comment by kristohberg** [comment]
@dboures like you pointed out, right now at each tick there could be many liquidity position structs (current size 125b) and with a stack frame of 4096 it might not be possible to target more than 32 liquidity position struct per instruction. 

The worst case scenario would be infinite many liquidity providers providing $1 liquidity at at tick. If someone wants to buy insurance worth $100,000 that would be extremely hard. I'm not even sure if a linked list of liquidity positions is the way to go. I think it is important that we try to explore a first in, first out approach for liquidity. 

**Idea**: we could have a liquidity pool at each tick, then annotate liquidity position accounts with some seniority. This way insurance buyers will just buy from the tick pool. Then premiums are paid according to seniority. So we need to keep an order of liquidity positions and keep track of the liquidity. Not sure about this but we could keep the order in the tick account maybe. We could have max 250 000 accounts if we only store a seed index ["sure-lp",pool,token,liquidity_id] [u32; 250 000] = 250 000*4. = 1_000_000
